"""Initial migration.

Revision ID: 8f00b5baf58a
Revises: 
Create Date: 2020-09-01 19:53:37.601141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f00b5baf58a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('ag', sa.Integer(), nullable=True))
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('actor', 'ag')
    # ### end Alembic commands ###
