"""Initial migration.

Revision ID: bb6842624219
Revises: 8f00b5baf58a
Create Date: 2020-09-01 19:54:13.110925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6842624219'
down_revision = '8f00b5baf58a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=True))
    op.drop_column('actor', 'ag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('ag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###
